name: base
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - anaconda-anon-usage=0.7.0=py313hfc0e8ea_101
  - annotated-types=0.6.0=py313h06a4308_0
  - aom=3.6.0=h6a678d5_0
  - archspec=0.2.3=pyhd3eb1b0_0
  - asttokens=3.0.0=py313h06a4308_0
  - attrs=24.3.0=py313h06a4308_0
  - beautifulsoup4=4.13.4=py313h06a4308_0
  - blas=1.0=openblas
  - bleach=6.2.0=py313h06a4308_0
  - boltons=24.1.0=py313h06a4308_0
  - bottleneck=1.4.2=py313hf0014fa_0
  - brotli-python=1.0.9=py313h6a678d5_9
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.19.1=h5eee18b_0
  - ca-certificates=2025.2.25=h06a4308_0
  - cairo=1.16.0=he5ede1b_6
  - certifi=2025.7.14=py313h06a4308_0
  - cffi=1.17.1=py313h1fdaa30_1
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - comm=0.2.1=py313h06a4308_0
  - conda=25.5.1=py313h78bf25f_0
  - conda-anaconda-telemetry=0.1.2=py313h06a4308_1
  - conda-anaconda-tos=0.1.3=py313h06a4308_0
  - conda-content-trust=0.2.0=py313h06a4308_1
  - conda-libmamba-solver=25.4.0=pyhd3eb1b0_0
  - conda-package-handling=2.4.0=py313h06a4308_0
  - conda-package-streaming=0.11.0=py313h06a4308_0
  - contourpy=1.3.1=py313hdb19cb5_0
  - cpp-expected=1.1.0=hdb19cb5_0
  - cryptography=44.0.1=py313h7825ff9_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - dav1d=1.2.1=h5eee18b_0
  - debugpy=1.8.11=py313h6a678d5_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - distro=1.9.0=py313h06a4308_0
  - et_xmlfile=1.1.0=py313h06a4308_1
  - executing=0.8.3=pyhd3eb1b0_0
  - expat=2.7.1=h6a678d5_0
  - fmt=9.1.0=hdb19cb5_1
  - fontconfig=2.14.1=h55d465d_3
  - fonttools=4.55.3=py313h5eee18b_0
  - freetype=2.13.3=h4a9f257_0
  - fribidi=1.0.10=h7b6447c_0
  - frozendict=2.4.2=py313h06a4308_0
  - graphite2=1.3.14=h295c915_1
  - greenlet=3.1.1=py313h6a678d5_0
  - harfbuzz=10.2.0=hdfddeaa_1
  - icu=73.1=h6a678d5_0
  - idna=3.7=py313h06a4308_0
  - ipykernel=6.29.5=py313h06a4308_1
  - ipython=9.1.0=py313h06a4308_0
  - ipython_pygments_lexers=1.1.1=py313h06a4308_0
  - jedi=0.19.2=py313h06a4308_0
  - jinja2=3.1.6=py313h06a4308_0
  - jpeg=9e=h5eee18b_3
  - jsonpatch=1.33=py313h06a4308_1
  - jsonpointer=2.1=pyhd3eb1b0_0
  - jsonschema=4.23.0=py313h06a4308_0
  - jsonschema-specifications=2023.7.1=py313h06a4308_0
  - jupyter_client=8.6.3=py313h06a4308_0
  - jupyter_core=5.8.1=py313h06a4308_0
  - jupyterlab_pygments=0.3.0=py313h06a4308_0
  - kiwisolver=1.4.8=py313h6a678d5_0
  - krb5=1.20.1=h143b758_1
  - lcms2=2.16=h92b89f2_1
  - ld_impl_linux-64=2.40=h12ee557_0
  - lerc=4.0.0=h6a678d5_0
  - libarchive=3.7.7=hfab0078_0
  - libavif=1.1.1=h5eee18b_0
  - libcurl=8.12.1=hc9e6f67_0
  - libdeflate=1.22=h5eee18b_0
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libglib=2.84.2=h37c7471_0
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h5eee18b_3
  - libmamba=2.0.5=haf1ee3a_1
  - libmambapy=2.0.5=py313hdb19cb5_1
  - libmpdec=4.0.0=h5eee18b_0
  - libnghttp2=1.57.0=h2d74bed_0
  - libopenblas=0.3.29=ha39b09d_0
  - libpng=1.6.39=h5eee18b_0
  - libsodium=1.0.18=h7b6447c_0
  - libsolv=0.7.30=he621ea3_1
  - libssh2=1.11.1=h251f7ec_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtiff=4.7.0=hde9077f_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp-base=1.3.2=h5eee18b_1
  - libxcb=1.17.0=h9b100fa_0
  - libxml2=2.13.8=hfdd30dd_0
  - lz4-c=1.9.4=h6a678d5_1
  - markdown-it-py=2.2.0=py313h06a4308_1
  - markupsafe=3.0.2=py313h5eee18b_0
  - matplotlib-base=3.10.0=py313h68cf311_1
  - matplotlib-inline=0.1.6=py313h06a4308_0
  - mdurl=0.1.0=py313h06a4308_0
  - menuinst=2.2.0=py313h06a4308_1
  - mistune=3.1.2=py313h06a4308_0
  - multi_key_dict=2.0.3=pyhd3eb1b0_0
  - narwhals=1.31.0=py313h06a4308_1
  - nbclient=0.10.2=py313h06a4308_0
  - nbconvert=7.16.6=py313h06a4308_0
  - nbconvert-core=7.16.6=py313h06a4308_0
  - nbconvert-pandoc=7.16.6=py313h06a4308_0
  - nbformat=5.10.4=py313h06a4308_0
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.6.0=py313h06a4308_0
  - nlohmann_json=3.11.2=h6a678d5_0
  - numexpr=2.11.0=py313he3a25fe_0
  - numpy=2.3.1=py313h3d1d590_0
  - numpy-base=2.3.1=py313hc428782_0
  - openjpeg=2.5.2=h0d4d230_1
  - openpyxl=3.1.5=py313h5eee18b_1
  - openssl=3.0.16=h5eee18b_0
  - packaging=24.2=py313h06a4308_0
  - pandas=2.2.3=py313h6a678d5_0
  - pandoc=2.12=h06a4308_3
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - parso=0.8.4=py313h06a4308_0
  - patsy=1.0.1=py313h06a4308_0
  - pcre2=10.42=hebb0a14_1
  - pexpect=4.9.0=py313h06a4308_0
  - pillow=11.3.0=py313hb1c3d2d_0
  - pip=25.0=py313h06a4308_0
  - pixman=0.40.0=h7f8727e_1
  - platformdirs=4.3.7=py313h06a4308_0
  - plotly=6.0.1=py313h7040dfc_0
  - plotly_express=0.4.1=py_0
  - pluggy=1.5.0=py313h06a4308_0
  - prompt-toolkit=3.0.43=py313h06a4308_0
  - prompt_toolkit=3.0.43=hd3eb1b0_0
  - psutil=5.9.0=py313h5eee18b_1
  - pthread-stubs=0.3=h0ce48e5_1
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pybind11-abi=5=hd3eb1b0_0
  - pycosat=0.6.6=py313h5eee18b_2
  - pycparser=2.21=pyhd3eb1b0_0
  - pydantic=2.10.3=py313h06a4308_0
  - pydantic-core=2.27.1=py313h4aa5aa6_0
  - pygments=2.19.1=py313h06a4308_0
  - pymysql=1.1.1=py313h06a4308_0
  - pyparsing=3.2.0=py313h06a4308_0
  - pysocks=1.7.1=py313h06a4308_0
  - python=3.13.2=hf623796_100_cp313
  - python-dateutil=2.9.0post0=py313h06a4308_2
  - python-fastjsonschema=2.20.0=py313h06a4308_0
  - python-jenkins=1.7.0=pyhd3eb1b0_0
  - python-tzdata=2025.2=pyhd3eb1b0_0
  - python_abi=3.13=0_cp313
  - pytz=2025.2=py313h06a4308_0
  - pyzmq=26.2.0=py313h6a678d5_0
  - readline=8.2=h5eee18b_0
  - referencing=0.30.2=py313h06a4308_0
  - reproc=14.2.4=h6a678d5_2
  - reproc-cpp=14.2.4=h6a678d5_2
  - requests=2.32.3=py313h06a4308_1
  - rich=13.9.4=py313h06a4308_0
  - rpds-py=0.22.3=py313h4aa5aa6_0
  - ruamel.yaml=0.18.10=py313h5eee18b_0
  - ruamel.yaml.clib=0.2.12=py313h5eee18b_0
  - scipy=1.15.3=py313h1ea73e7_0
  - seaborn=0.13.2=py313h06a4308_3
  - setuptools=72.1.0=py313h06a4308_0
  - simdjson=3.10.1=hdb19cb5_0
  - six=1.17.0=py313h06a4308_0
  - soupsieve=2.5=py313h06a4308_0
  - spdlog=1.11.0=hdb19cb5_0
  - sqlalchemy=2.0.41=py313h00e1ef3_0
  - sqlite=3.45.3=h5eee18b_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - statsmodels=0.14.4=py313h5eee18b_0
  - tinycss2=1.4.0=py313h06a4308_0
  - tk=8.6.14=h39e8969_0
  - tornado=6.5.1=py313h5eee18b_0
  - tqdm=4.67.1=py313h7040dfc_0
  - traitlets=5.14.3=py313h06a4308_0
  - truststore=0.10.0=py313h06a4308_0
  - typing-extensions=4.12.2=py313h06a4308_0
  - typing_extensions=4.12.2=py313h06a4308_0
  - tzdata=2025a=h04d1e81_0
  - urllib3=2.3.0=py313h06a4308_0
  - wcwidth=0.2.13=py313h06a4308_0
  - webencodings=0.5.1=py313h06a4308_2
  - wheel=0.45.1=py313h06a4308_0
  - xlrd=2.0.1=pyhd3eb1b0_1
  - xlsxwriter=3.2.3=py313h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-libxext=1.3.6=h9b100fa_0
  - xorg-libxrender=0.9.12=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - yaml-cpp=0.8.0=h6a678d5_1
  - zeromq=4.3.5=h6a678d5_0
  - zlib=1.2.13=h5eee18b_1
  - zstandard=0.23.0=py313h2c38b39_1
  - zstd=1.5.6=hc292b87_0
