name: base
channels:
  - defaults
  - conda-forge
dependencies:
  - seaborn
  - sqlalchemy
  - xlsxwriter
  - pandas
  - ipykernel
  - python-jenkins
  - xlrd
  - openpyxl
  - nbformat
  - nbconvert
  - pymysql
  - plotly_express
