name: osm-analytics
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8.5
  - ipykernel
  - nbconvert
  - nbformat
  - openpyxl
  - pandas
  - plotly_express
  - pymysql
  - python-jenkins
  - seaborn
  - sqlalchemy
  - xlrd
  - xlsxwriter
