name: base
channels:
  - defaults
  - conda-forge
dependencies:
  - ipykernel=6.29.5
  - nbconvert=7.16.6
  - nbformat=5.10.4
  - openpyxl=3.1.5
  - pandas=2.2.3
  - plotly_express=0.4.1
  - pymysql=1.1.1
  - python-jenkins=1.8.3
  - seaborn=0.13.2
  - sqlalchemy=2.0.41
  - xlrd=2.0.1
  - xlsxwriter=3.2.3

