apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ./argowf
- ./mysql
- ./db-provisioning/db-provisioning-job.yaml
- ./workflow-templates
# - TODO: CronWorkflows for periodic tasks

transformers:
- label-transformer.yaml

