apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
- includeSelectors: true
  pairs:
    app: osm-analytics

resources:
- ./argowf
- ./mysql
- ./db-provisioning/db-provisioning-job.yaml
# - TODO: Worflow templates for OSM analytics
# - TODO: CronWorkflows for periodic tasks

