apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ./mysql
- ./db-provisioning/db-provisioning-job.yaml
- ./workflow-templates
- ./cron-workflows

transformers:
- label-transformer.yaml

