apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: bugzilla-report
  namespace: workflow-runs
spec:
  # Run daily at 13:35 CET
  timezone: Europe/Paris
  schedules:
  - "35 8 * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 7
  failedJobsHistoryLimit: 7
  workflowSpec:
    workflowTemplateRef:
      name: bugzilla-report

